name: Testing...
on: [push]
jobs:
  End-to-End-test:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: yarn install
      - run: yarn test
